# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-07-19 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='price_track_data',
            fields=[
                ('p_email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('p_status', models.CharField(max_length=15)),
            ],
        ),
    ]
