# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-07-19 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_track_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='price_track_data',
            new_name='trackdata',
        ),
    ]
