# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-07-19 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_track_app', '0002_auto_20190719_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackdata',
            name='p_email',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
